name: "Carbon Gate"
description: >-
  Estimate carbon emissions of ML training jobs and gate PR merges based on
  configurable thresholds. Auto-applies Crusoe AI efficiency patches to PR
  branches when CRUSOE_API_KEY is set.
  REQUIRED workflow permissions: contents: write  pull-requests: write
author: "Carbon Gate Team"
branding:
  icon: "cloud"
  color: "green"

inputs:
  github-token:
    description: "GitHub token for posting PR comments"
    required: true
  api-endpoint:
    description: "Carbon Gate API endpoint URL"
    required: false
    default: "https://bit-manip-hackeurope.vercel.app"
  org-api-key:
    description: "Organization API key for Carbon Gate"
    required: true
  crusoe-api-key:
    description: "Crusoe Cloud API key for AI-powered carbon-efficiency code suggestions"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        pip install requests pyyaml

    - name: Run Carbon Gate check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        API_ENDPOINT: ${{ inputs.api-endpoint }}
        ORG_API_KEY: ${{ inputs.org-api-key }}
        CRUSOE_API_KEY: ${{ inputs.crusoe-api-key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      run: |
        python ${{ github.action_path }}/gate_check.py
